general:
  generate_plots: True
  n_trajectories: 1  # generate multiple trajectories
  debug: False  # Enable debug outputs
quadrotor:
  mass: 0.7    # [kg]
  inertia: [ .03, .03, .06 ]  # [kg m^2]
  max_thrust_per_motor: 7.0 # [N]
  rotor_drag_coeff: 0.13  # [Nm/N]
  arm_length: 0.15
trajectory:
  type: "geometric"  # "random", "geometric"
  duration: 60.0
  dt: 0.02    # [s] trajectory will be sampled at this frequency
  seed: -1    # set to -1 for random seed
  bound_min: [ -4.0, -4.0, 1.0 ]
  bound_max: [ 8.0, 5.0, 5.0 ]
  random: # "random" trajectory specific settings
    freq_x: 0.9
    freq_y: 0.7
    freq_z: 0.7
  dt_gen: 0.01 # numerical diff is done with this spacing, does not affect dt of saved trajectory
